spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password